language: python
python:
    - "3.2"
    - "3.3"
before_install:
    - "easy_install --version"
    - "pip freeze"
install: "pip install -r test-requirements.txt"
before_script: "pip freeze -r test-requirements.txt"
script: "python -m unittest"
