language: python
python:
    - "3.2"
    - "3.3"
before_install:
    - "easy_install --version"
    - "pip freeze"
    - "travis_retry pip install -U setuptools"
    - "cd `mktemp -d`"
    - "travis_retry wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py"
    - "travis_retry python get-pip.py"
    - "cd $OLDPWD"
    - "pip --version"
    - "easy_install --version"
install: "pip install -r test-requirements.txt"
before_script: "pip freeze -r test-requirements.txt"
script: "python -m unittest"
